### ISSUE TITLE
Gnome mmkeys plugin doesn't work in Xubuntu

### ISSUE THREAD

**Issue by cossio** [squentin/gmusicbrowser#104]
When I try to activate Gnome mmkeys plugin, I get the following error:

Error :
Can't find the dbus Settings Daemon for gnome or MATE

I am running Xubuntu 15.04, gmusicbrowser v1.1.13 (the version available in the vivid repositories).

Can I solve this? Do I have to install a missing package?

**Comment by squentin** [comment]
I think xubuntu by default uses the xfce desktop not gnome or MATE. So it's normal that it doesn't work.
I don't know if xfce has an API for doing this.
In any case you can bind the keys manually (in xfce) to run commands like "gmusicbrowser -cmd PlayPause" (or other commands : PrevSong, NextSong and Stop)

see https://help.ubuntu.com/community/XfceMultimediaKeys for some help doing this (it may be a bit old, I haven't tried it).

**Comment by cossio** [comment]
Maybe this shouldn't be closed until mm keys works in Xubuntu? After all, gmusicbrowser is the default music player in Xubuntu.

**Comment by squentin** [comment]
Well, for one, the plugin is called gnome mmkeys, though of course I could rename it.

The real problem is that as far as I'm aware there is no similar way of telling the system "this app wants to use the multimedia keys" in other desktops. I may very well be wrong, as I don't follow the various desktops, if there is a way, let me know.

The only alternative, if I'm not mistaken, is to use a function that capture every key that is pressed, anywhere, and I don't like that too much. For me this is the job of the desktop/window manager.

**Comment by wdog** [comment]
I've found this script and it works fine

https://raw.githubusercontent.com/wilson-bl-santos/xubuntugeek/master/gmusicbrowser/gmusicbrowser-mmkeys_v2.sh

as described here http://unix.stackexchange.com/questions/321258/cant-find-the-dbus-settings-daemon-gmusicbrowser-in-debian-jessie-with-xfce/321319
