### ISSUE TITLE
openbsd Compilation Error

### ISSUE THREAD

**Issue by ralphee** [squentin/gmusicbrowser#163]
trying to compile from source and get [this](http://ix.io/1C5H)

**Comment by squentin** [comment]
Thanks for reporting this, it seems openbsd's install command is a bit more strict with its options, and doesn't allow -p and -d option together because in that case the -p option is useless. Not sure why I used it, probably copied it from somewhere without thinking.

Can you replace all the "install -pd" by "install -d" in the Makefile and see if everything else works ?

**Comment by ralphee** [comment]
> Thanks for reporting this, it seems openbsd's install command is a bit more strict with its options, and doesn't allow -p and -d option together because in that case the -p option is useless. Not sure why I used it, probably copied it from somewhere without thinking.
> 
> Can you replace all the "install -pd" by "install -d" in the Makefile and see if everything else works ?

yup did the trick o/

**Comment by squentin** [comment]
I've committed the changes: 6924e4911b4315ebfe8d017fdfa47444bf45e72d
