### ISSUE TITLE
Segmentation fault: on Ctrl+F and start input

### ISSUE THREAD

**Issue by Hukuta** [squentin/gmusicbrowser#168]
My steps:
1) Open player with loaded music library (Layout - conz aardvark)
2) Press Ctrl+f, see input field for searching
3) Press a key "s" (for example) - see immediately crash

> invalid iter -- stamp -463496032 does not match requested 93982010875040 at /usr/bin/../share/gmusicbrowser/gmusicbrowser_list.pm line 1491.
> [1]    14881 segmentation fault (core dumped)  gmusicbrowser

**Comment by squentin** [comment]
I'm pretty sure it's an old bug that I fixed long ago (d26f6adea435104382adc24a975e2a52b7213ec5), but is not in the "latest" release because I haven't done a release in way too long. There is not that much new in since, but still you should use the git version, it's rather easy to use, as there is no compilation (except for translations).

Anyway, I'm finishing the gtk3 version, so I'll make a release when it's mostly ok, in a few weeks at the most.

**Comment by Hukuta** [comment]
Can confirm that in github "master" version this issue is fixed
