### ISSUE TITLE
Move to the Database System For Library

### ISSUE THREAD

**Issue by justperfection** [squentin/gmusicbrowser#181]
Currently, GMB using file system for storing the library. This approach has some cons:

- On large archive the open and close process is painfully slow. Currently I have loaded +5TB archive and it can take more than one minute to open and +30 seconds to close (on 520MB/480MB SSD).
- Saving the entire library on close event is a bad idea:
    - We have unnecessary disk write by saving the entire library again.
    - If we don't close the program we can lose some data such as play count and ..., because GMB only saves the library on close.
    - Using plugins such as autosave is a wrong solution while it cannot guarantee that all of our data will be saved (what if the system goes off and we are between the autosave time duration).

### Solution

Using Database system instead of file system can solve the problem:

- Can avoid unnecessary disk write.
- Changes can be written when events happen (we don't need autosave plugin anymore).
- Close will be fast since we don't need to save anything on close.
- Open will be faster since the file system for large file is slower.
- We don't lose anything when system goes off and we didn't close the GMB.

**Comment by RomanHargrave** [comment]
SQlite3 is the typical solution for this

**Comment by squentin** [comment]
First "using file system for storing the library" is what databases do, it's all in how they do it.

For the history behind it:
Long ago, when working on version 1.1, I experimented with using a sqlite database, what I remember was while some things worked fine, I ran into performances issues for the weighted random system, as it uses some non-basic math, I couldn't ask sql to compute the whole expression and had instead to ask sql for each of the values and do the computation in perl, there was too much overhead for something that must be done for tens of thousands of songs and must be nearly instant. I think there was other tests that while fast enough, were not that fast, overall I was not impressed.
That was the main reason I didn't used sql, though I also favored having an easily accessible text file that contains everything, so easy to control and to backup. And I guess I wanted to experiment with doing everything in perl too.
Now that was some time ago, and I mostly have no experience in sql, so maybe I overlooked something at the time or maybe it has changed since. But I came up with the current system instead: code generation to efficiently handle the various type of data, and saving into an easy to read all-in-one text file. And while the code could use some cleaning up, I'm rather happy with it.

```
    Can avoid unnecessary disk write.
    Changes can be written when events happen (we don't need autosave plugin anymore).
    Close will be fast since we don't need to save anything on close.
```
All this could be mostly avoided with relatively small changes, I thought about it a few times. For the song database part, every change is controlled so it's easy to do something when a song is changed, like saving that song's metadata to a "changes" file (until it gets too big, then you just replace the whole file). The options part is a bit more work, as some parts of the code just access the Options directly, but it should be possible too. 

`    We don't lose anything when system goes off and we didn't close the GMB.`

With the autosave plugin with a low enough interval (I have mine to 12min), there is really not that much that you can lose.


`    Open will be faster since the file system for large file is slower.`

Not sure if it's the file size that is the problem. If it is the command line option +gzip or +xz should help. They compress the save file, I haven't made it on by default because of the frequent saves by the autosave plugin, I should investigate to if it's a good idea. The backups are always compressed. Note that if gmb loads from a compressed save file it will save it compressed.


Anyway, I don't plan on switching to a sql database currently.
Though in case someone wanted to do it (I can't stop you) it shouldn't be too hard to switch, as it mostly involve changing the generated code, and it's all in the same place, though there is a lot of it, and I guess it's rather hard to understand how it works, as I said, the code could use some cleanups, and a lot of comments (I've just checked, there are no comment explaining how this works).

**Comment by justperfection** [comment]
Database is definitely faster than normal file system since it can use indexing.

Just to give you an example that how this move can affect the performance:
I've installed Yarock (using SQLite) with 5TB of library and here is the result:

| App          | Open | Close |
| - | - | - |
| gmusicbrowser | + one minute | +30 seconds |
| Yarock | under 3 seconds | under 1 second |

**Comment by squentin** [comment]
Databases are not magic, they are using the normal filesystem.
I know a lot of the time loading gmb is parsing the text for escape characters, things like that, I could just dump the perl variables holding the data, that would be much faster. But it would have a few drawbacks, 1. there are a few things like reclaiming space from deleted songs/strings that is not done, it's done indirectly with saving/loading, so it would have to be done, that is complicated code that I'd rather avoid. 2. nobody could read the saved data other than gmb 3. changing that format in future version would get much more complicated.

Now of course, you might say it's what databases do, and I should let them do it for me. But the thing is, startup/close time is not a high priority for me. It's always running, and I'm never waiting for it to start (apart from when I'm testing changes but that is not for end-users), and I think it's that way for a lot of users.

What I care about is speed when actually using it, and as I said, I couldn't, at the time, make it work fast enough for the weighted random system (with the math it is currently using at least), and in general the speed was not that great.
So unless the libraries have been improved, or I missed something, I would have at the very least to change the way the weighted random system works (which I plan to btw, to optionally let users write the expression, but that could make evaluating it via sql even harder). Even then, it seems I'm limited in what I can do quickly with sql, which is something I really don't like.
And also it would be quite some work, and I'd rather work on other stuff (there is so much I've been wanting to add).

Did you try with the +gzip or +xz option ? Though it probably won't change much on a ssd.

**Comment by justperfection** [comment]
How can I enable that option?

**Comment by squentin** [comment]
> How can I enable that option?

Just launch it from a terminal with "gmusicbrowser +gzip", the next save will be compressed with gzip (or xz with +xz). I think you can also just compress the save file manually with gzip or xz. When loaded from a compressed savefile it will save with the same compression, so the option sticks, use -gzip to revert to non-compressed.

**Comment by justperfection** [comment]
I did that but it took like 4 seconds more to load.
It's okay. I only open and close GMB once a day. I thought by making open and close faster it could make this great music player better. I can live with that.
Thanks for the time you put into creating this great music player.
