### ISSUE TITLE
Selected a layout, can no longer change layouts

### ISSUE THREAD

**Issue by indeedwatson** [squentin/gmusicbrowser#191]
I don't remember which I selected, but as you can see in the screenshot there's nowhere for me to click to change to another layout
![1608143446](https://user-images.githubusercontent.com/10749504/102391003-e3e40700-3fb3-11eb-9293-c6730eed900c.png)

**Comment by morgannunan** [comment]
I'm not sure what layout this is, but I have had similar problems before. Try pressing f10 and see if any menu pops up. If that doesn't work, run gmusicbrowser -cmd OpenPref and this will open the preferences, where you can change the layout.

**Comment by indeedwatson** [comment]
Thank you, does this just happen randomly with any layout? I thought it was an oversight of this particular one (turns out to be rhythmbox compact).

**Comment by morgannunan** [comment]
That looks like normal Rhythmbox to me, not compact. But I have a menu bar at the top. You don't have a menu bar?

**Comment by indeedwatson** [comment]
I might have misread which was selected. And I do now, it must have bugged out.

**Comment by squentin** [comment]
I took a quick look, the "rhythmbox compact" layout is "based on" the rhythmbox one, but it's not done correctly.
The "based on" feature is a bit rough, and if you don't use some boxes from the parent layout you need to unset them.
In this case it can't find the toplevel box because a few other boxes from the rhythmbox layout are not used so don't have a parent, so are technically toplevel too (there is a warning on the terminal), so it picks one probably somewhat randomly, so you might not get the same layout every time.
I'll have to fix the layout, probably make it not use the "based on" feature and just copy the parts that are needed.

**Comment by indeedwatson** [comment]
> and if you don't use some boxes from the parent layout you need to unset them.

What do you mean by this? Is it something to be done from the user side? Is the only way to customize layouts via config files?

**Comment by squentin** [comment]
> > and if you don't use some boxes from the parent layout you need to unset them.
> 
> What do you mean by this? Is it something to be done from the user side? Is the only way to customize layouts via config files?

Sorry it was confusing, I was talking from the point of view of the layout author. The layout is broken, I didn't check it properly when I added it. I should make the error fatal or at least show the error in a dialog so that it isn't ignored.
Yes the only way to customize a layout is via the layout file, though the layout can offer some customization options, and of course there is a lot of configuration available to users in many widgets.

**Comment by indeedwatson** [comment]
Makes sense, thank you. I'd like to make a layout but at the moment the documentation seems a bit overwhelming, I might take an existing one and tinker with it when I have some time.

**Comment by squentin** [comment]
fixed with 3ad1eaf54757f1 / 9ce15de49c & 15a801c5bbafa6 / af04224149d
