### ISSUE TITLE
Can't post on forum: Database Error

### ISSUE THREAD

**Issue by MountainX** [squentin/gmusicbrowser#230]
Since 3 days ago I have not been able to post on the forum. I was going to add my solution to this post:

https://forum.gmusicbrowser.org/index.php?topic=77610.0

The error I got 3 days ago, and again today is:

Database Error

    gmusicbrowser Forum
    ► Main board
    ► Questions

Database Error
Please try again. If you come back to this error screen, report the error to an administrator.

Since I could not post there, I put my solution here:

[(1) How to copy music files and playlist to Android device? (GMusicBrowser) : linuxquestions](https://www.reddit.com/r/linuxquestions/comments/t2e28b/how_to_copy_music_files_and_playlist_to_android/hym0jve/?context=3 "(1) How to copy music files and playlist to Android device? (GMusicBrowser) : linuxquestions")

**Comment by squentin** [comment]
I could post a link to your reply.
Don't know what the problem was, though I know the forum is a bit fragile.
I've moved the forum to raspberry pi 14 months ago, and I choose to upgrade the forum software to a RC rather than downgrading php, but it has not been smooth. I've just noticed they finally released a stable version in february so I'll upgrade soon, hopefully it will be better.
