### ISSUE TITLE
Shortcut does not execute associated action

### ISSUE THREAD

**Issue by nicolas-raoul** [squentin/gmusicbrowser#84]
- Set up a shortcut Space->Play/Pause
- Close Settings dialog
- Press Space
- [PROBLEM] Current song restarts from beginning, does not pause
- Restart gmusicbrowser
- Same problem

Ubuntu 2014.04

**Comment by howdystranger** [comment]
I also have this problem! It is super annoying - to the point where I don't use this program. Is there some shortcut for this?

**Comment by squentin** [comment]
The problem is that currently the keyboard shortcuts that you set up in gmb are only "low-priority", that is they only take effect if the widget that has the focus doesn't react to the key press. So trying to set a shortcut for the Space will rarely do anything, as space will most often do something such as -activate the button that has the focus -enter a space in a text entry -play the selected song in a song list.

I've been meaning to add a way to set up "high priority" shortcuts that overrides the currently focused widget (unless it's something like a text entry), but I've been hesitating between doing it via a checkbox for each shortcut, or doing it "smartly" where maybe shortcuts without modifiers (shift/alt/ctrl/win) are automatically high-priority shortcuts, or even making them all "high priority" shortcuts.

Also, I'm a bit reluctant of letting users override keys that are used for keyboard navigation, like space, tab, arrows keys, enter...

I guess I'll implement it with a checkbox for each shortcuts, with a good tooltip to explain the consequences.

In the meantime, my advice would be to use win-space instead as a shortcut.

**Comment by howdystranger** [comment]
Thanks for your response! Nice to know the reasons why the program does it this way.
(I wouldn't be too worried about the consequences - pressing space to play/pause is default behaviour in almost every audio program I've ever used, but I guess there could be some problems with other keyboard/mouse shortcuts.)
