### ISSUE TITLE
Wishlist: When renaming a file and it gets found again do not remove it from saved lists

### ISSUE THREAD

**Issue by yennor** [squentin/gmusicbrowser#87]
I noticed that gmusicbrowser is able to notice when a file gets renamed.
At least at the console it writes messages like:
Found missing song, formerly '/home/blabla/blabla_old.mp3'
Unfortunately when that song belonged to a saved playlist, it gets removed from that playlist. Would be nice, if gmusicbrowser notices that a file got moved or renamed, that it also readds it to the playlists it was in

**Comment by squentin** [comment]
The commit a45e96a37583adcb should mostly fix this.
Now when adding songs, if the new song has a title and artist, it will check for a match already in the library, and if the file for that match is missing it will simply update its path and file name.

So I think this issue is fixed: provided you don't first remove the song, the song will stay in the saved lists
